# Required connection configs for Kafka producer, consumer, and admin
bootstrap.servers=pkc-12576z.us-west2.gcp.confluent.cloud:9092
security.protocol=SASL_SSL
sasl.mechanisms=PLAIN
sasl.username=IDS4B5OFI6H6TLTF
sasl.password=cfltsDxEP2pqwLT+W6hUfMdsrp7gF4liIUjuFG+5GfKU8xKfmqrkqGUYKvOMVA3Q

# Best practice for higher availability in librdkafka clients prior to 1.7
session.timeout.ms=45000

client.id=ccloud-python-client-420fdc0c-4b6c-4b49-bf9d-90a9cbff18f5
